/**
 * This simple program receives a two column file such as the ones
 * generated by captcp or tcptrace to extract measures from pcap files,
 * and makes simple statistics accordingly to the amount of times a key is 
 * seen in the file.
 * In the throughput file the key: approximate integer value in Kilobytes (i.e. 10.123 Kb -> 10) in a specific time
 * In the inflight data file the key: number of segments unacknowledged.
 * 
 * It's main goal is to check between different simulation outputs in the case 
 * looking at the graphs is insufficient
 */


import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.Map;
import java.util.TreeMap;

public class Main {
	
	public static TreeMap<String, Integer> map = new TreeMap<String, Integer>();
	
	/**
	 * @param args Throughput data file
	 * @throws IOException 
	 * @throws FileNotFoundException 
	 */
	public static void main(String[] args) throws FileNotFoundException {
		
		if (args.length < 1) {
			System.err.println("tputstat <tput data file>");
			System.exit(-1);
		}
		
		//tries to open the text file passed as argument.
		try {
			FileReader fr = new FileReader(args[0]);
			try (BufferedReader br = new BufferedReader(fr)) {
				String line;	    	   
			    int line_count = 0;
			    double avg = 0;
			    while ((line = br.readLine()) != null) {
			    	line_count++;
			    	
			    	//The integer value of seconds will be used as the key for the map
			    	String delimiter = " ";
			    	String[] temp;
			    	String poskey;
			    	
			    	temp = line.split(delimiter);
			    	poskey = temp[1]; //second column
			    	avg += Double.parseDouble(poskey); 
			    	delimiter = "\\.";
			    	temp = poskey.split(delimiter);
			    	poskey = temp[0];
			    	
			    	//If it is a new key, adds it with one occurrence.
			    	if (!map.containsKey(poskey)){
			    		map.put(poskey, new Integer(1));
			    	}
			    	else { //else adds one to the value.
			    		Integer aux = map.get(poskey) + 1;
			    		//map.remove(poskey);
			    		map.put(poskey, aux);
			    	}
			    }
			    for (Map.Entry<String, Integer> entry : map.entrySet()) {
			    	int val = entry.getValue().intValue();
			    	double d = (double) val;
			    	double percent =( d * 100.0)/(double)line_count;
			    	DecimalFormat numberFormat = new DecimalFormat("#.00");
			    	System.out.println("Key = " + entry.getKey() + " -- Percentage : " + numberFormat.format(percent) + " %");
			    }
			    avg = avg/line_count;
			    
			    System.out.println("Average = " + avg);
			}
			catch (IOException ioe) {
				System.err.println("tputstat: input/output error");
			}
		}
		catch (FileNotFoundException fe){
			System.err.println("tputstat: data file does not exist");
		}
	}

}

